NAME: grocy
LAST DEPLOYED: Thu May 15 21:36:59 2025
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
app-template:
  common:
    configMaps: {}
    controllers: {}
    defaultPodOptions:
      affinity: {}
      annotations: {}
      automountServiceAccountToken: true
      dnsConfig: {}
      dnsPolicy: ""
      enableServiceLinks: false
      hostAliases: []
      hostIPC: false
      hostNetwork: false
      hostPID: false
      hostname: ""
      imagePullSecrets: []
      labels: {}
      nodeSelector: {}
      priorityClassName: ""
      restartPolicy: ""
      runtimeClassName: ""
      schedulerName: ""
      securityContext: {}
      tolerations: []
      topologySpreadConstraints: []
    enforceServiceAccountCreation: false
    global:
      annotations: {}
      labels: {}
    ingress: {}
    networkpolicies: {}
    persistence: {}
    rawResources: {}
    rbac: {}
    route: {}
    secrets: {}
    service: {}
    serviceAccount:
      annotations: {}
      create: false
      extraServiceAccounts: {}
      labels: {}
      name: ""
    serviceMonitor: {}
  controllers:
    grocy:
      containers:
        grocy:
          env:
            APPDATA: /config
            PGID: 1000
            PUID: 1000
            TZ: Asia/Dubai
          image:
            repository: lscr.io/linuxserver/grocy
            tag: 4.2.0
          resources:
            limits:
              memory: 799M
            requests:
              cpu: 5m
              memory: 799M
  global: {}
  ingress:
    grocy:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      className: nginx
      hosts:
      - host: grocy.themainfreak.com
        paths:
        - path: /
          service:
            identifier: grocy
            port: http
      tls:
      - hosts:
        - grocy.themainfreak.com
        secretName: grocy-tls-certificate
  persistence:
    data:
      enabled: true
      existingClaim: grocy
      globalMounts:
      - path: /config
  service:
    grocy:
      controller: grocy
      ports:
        http:
          port: 80
volsync-backups:
  global: {}

HOOKS:
MANIFEST:
---
# Source: grocy/charts/volsync-backups/templates/ResticSecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "grocy-volsync-secret"
  namespace: "default"
type: Opaque
stringData:
  RESTIC_REPOSITORY: "/repository/grocy"
  RESTIC_PASSWORD: "1234"
---
# Source: grocy/charts/volsync-backups/templates/PersistentVolumeClaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "grocy"
  namespace: "default"
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: "ReplicationDestination"
    apiGroup: "volsync.backube"
    name: "grocy-dst"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: ceph-block
---
# Source: grocy/charts/app-template/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: grocy
  labels:
    app.kubernetes.io/instance: grocy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grocy
    app.kubernetes.io/service: grocy
    helm.sh/chart: app-template-3.5.1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: grocy
    app.kubernetes.io/instance: grocy
    app.kubernetes.io/name: grocy
---
# Source: grocy/charts/app-template/templates/common.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  labels:
    app.kubernetes.io/component: grocy
    app.kubernetes.io/instance: grocy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grocy
    helm.sh/chart: app-template-3.5.1
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: grocy
      app.kubernetes.io/name: grocy
      app.kubernetes.io/instance: grocy
  template:
    metadata:
      labels: 
        app.kubernetes.io/component: grocy
        app.kubernetes.io/instance: grocy
        app.kubernetes.io/name: grocy
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers: 
        - env:
          - name: APPDATA
            value: /config
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          - name: TZ
            value: Asia/Dubai
          image: lscr.io/linuxserver/grocy:4.2.0
          name: grocy
          resources:
            limits:
              memory: 799M
            requests:
              cpu: 5m
              memory: 799M
          volumeMounts:
          - mountPath: /config
            name: data
      volumes: 
        - name: data
          persistentVolumeClaim:
            claimName: grocy
---
# Source: grocy/charts/app-template/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grocy
  labels:
    app.kubernetes.io/instance: grocy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grocy
    helm.sh/chart: app-template-3.5.1
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "grocy.themainfreak.com"
      secretName: "grocy-tls-certificate"
  rules:
    - host: "grocy.themainfreak.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: grocy
                port:
                  number: 80
---
# Source: grocy/charts/volsync-backups/templates/ReplicationDestination.yaml
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: grocy-dst
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: grocy-volsync-secret
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block
    cacheStorageClassName: ceph-block
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: "1Gi"
    storageClassName: ceph-block
    accessModes: ["ReadWriteOnce"]
    capacity: "1Gi"
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
---
# Source: grocy/charts/volsync-backups/templates/ReplicationSource.yaml
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: grocy
  namespace: default
spec:
  sourcePVC: grocy-pvc
  trigger:
    schedule: "0 0 * * *"
  restic:
    repository: grocy-volsync-secret
    volumeSnapshotClassName: ceph-block
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

