app-template:
  controllers:
    grocy:
      containers:
        grocy:
          image:
            repository: lscr.io/linuxserver/grocy
            tag: "4.2.0"

          env:
            TZ: Asia/Dubai
            PUID: 1000
            PGID: 1000
            APPDATA: /config

          resources:
            requests:
              cpu: 5m
              memory: 799M
            limits:
              memory: 799M

  service:
    grocy:
      controller: grocy
      ports:
        http:
          port: 80

  ingress:
    grocy:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # Homepage auto-discovery annotations
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Grocy"
        gethomepage.dev/description: "Grocery & household management"
        gethomepage.dev/group: "Utilities"
        gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/loganmarchione/homelab-svg-assets@latest/assets/grocy.svg"
        gethomepage.dev/widget.type: "grocy"
        gethomepage.dev/widget.url: "https://grocy.themainfreak.com"
      hosts:
        - host: &host grocy.themainfreak.com
          paths:
            - path: /
              service:
                identifier: grocy
                port: http
      tls:
        - hosts:
            - *host
          secretName: grocy-tls-certificate

  persistence:
    data:
      enabled: true
      existingClaim: grocy
      globalMounts:
        - path: /config


