apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-mariadb-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vaultwarden-fields
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-mariadb-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          k8s.mariadb.com/watch: ""
      type: Opaque
  data:
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: case10-mariadb-item-id  # Replace with actual Vaultwarden item ID
        property: user_password
    - secretKey: MARIADB_ROOT_PASSWORD
      remoteRef:
        key: case10-mariadb-item-id  # Replace with actual Vaultwarden item ID
        property: root_password
    - secretKey: MARIADB_REPL_PASSWORD
      remoteRef:
        key: case10-mariadb-item-id  # Replace with actual Vaultwarden item ID
        property: repl_password
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: case10-minio-item-id    # Replace with actual Vaultwarden item ID
        property: access_key
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: case10-minio-item-id    # Replace with actual Vaultwarden item ID
        property: secret_key
