apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-tls-converter
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-tls-converter
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-tls-converter
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-tls-converter
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-tls-converter
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-tls-converter
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      annotations:
        "helm.sh/hook": pre-install,pre-upgrade
        "helm.sh/hook-weight": "-5"
    spec:
      serviceAccountName: {{ .Release.Name }}-tls-converter
      restartPolicy: OnFailure
      containers:
      - name: convert-tls
        image: bitnami/kubectl:latest
        command:
          - /bin/bash
          - -c
          - |
            set -e
            SECRET_NAME="{{ .Release.Name }}-selfsigned-certificate"
            NAMESPACE="{{ .Release.Namespace }}"
            echo "Waiting for secret $SECRET_NAME in namespace $NAMESPACE..."
            for i in {1..60}; do
              if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" 2>/dev/null; then
                echo "Secret found!"
                break
              fi
              if [ $i -eq 60 ]; then
                echo "Secret not found after 120 seconds"
                exit 1
              fi
              echo "Attempt $i/60: waiting for secret..."
              sleep 2
            done
            echo "Checking TLS key format..."
            kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath='{.data.tls\.key}' | base64 -d > /tmp/tls.key
            if grep -q "BEGIN RSA PRIVATE KEY" /tmp/tls.key; then
              echo "Converting PKCS#1 to PKCS#8..."
              apt-get update >/dev/null 2>&1 && apt-get install -y openssl >/dev/null 2>&1
              openssl pkcs8 -topk8 -nocrypt -in /tmp/tls.key -out /tmp/tls.key.pkcs8
              ENCODED_KEY=$(base64 -w0 < /tmp/tls.key.pkcs8)
              kubectl patch secret "$SECRET_NAME" -n "$NAMESPACE" -p "{\"data\":{\"tls.key\":\"$ENCODED_KEY\"}}"
              echo "Secret patched successfully"
            else
              echo "Key format is already correct"
            fi
