# create replication source for vaultwarden volsync for rustic backup

apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden
  namespace: {{ .Release.Namespace }}
spec:
    sourcePVC: vaultwarden-config
    trigger:
      schedule: "*/20 * * * *"
    restic:
      repository: nfs://192.168.0.41/nfs
      volumeSnapshotClassName: ceph-block
