# create replication source for vaultwarden volsync for rustic backup

apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden
  namespace: {{ .Release.Namespace }}
spec:
    source:
      persistentVolumeClaim:
        name: vaultwarden-config
        namespace: {{ .Release.Namespace }}
    trigger:
      schedule:
      # every 20 minutes
        cron: "*/20 * * * *"
    restic:
      repository: nfs://192.168.0.41/nfs
      volumeSnapshotClassName: ceph-block
