---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name vaultwarden-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local.:5432/vaultwarden
        ADMIN_TOKEN: {{` "{{ .VAULTWARDEN_ADMIN_TOKEN }}" `}}
        # Postgres Init
        INIT_POSTGRES_DBNAME: vaultwarden
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: {{` "{{ .POSTGRES_USER }}" `}}
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: vaultwarden
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: vaultwarden
        property: POSTGRES_PASS
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: vaultwarden
        property: POSTGRES_SUPER_PASS
    - secretKey: VAULTWARDEN_ADMIN_TOKEN
      remoteRef:
        key: vaultwarden
        property: VAULTWARDEN_ADMIN_TOKEN