apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vaultwarden
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: {{ .Release.Name }}
