---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
spec:
  accessModes: ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "vaultwarden-dst"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "ceph-block"