---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "vaultwarden-dst"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "vaultwarden-volsync-secret"
    copyMethod: Snapshot
    volumeSnapshotClassName: "ceph-blockpool"
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: "2Gi"
    storageClassName: "ceph-block"
    accessModes: ["ReadWriteOnce"]
    capacity: "1Gi"
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true