# create replication source for vaultwarden volsync for rustic backup

apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
    sourcePVC: vaultwarden-pvc
    trigger:
      schedule: "0 0 * * *"
    restic:
      repository: vaultwarden-volsync-secret
      volumeSnapshotClassName: ceph-block
      copyMethod: Snapshot
      moverSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
