{{- if .Values.customServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-custom
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: volsync
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: metrics
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    path: /metrics
    port: 8080
    scheme: http
  selector:
    matchLabels:
      control-plane: volsync-controller
{{- end }}
