apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.renovate.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .password }}" # Access the password from the fetched secret
  data:
    - secretKey: password # The key to store the fetched value as
      remoteRef:
        key: github-repo-creds # The name of the existing Kubernetes Secret
        property: password # The key within the secret to fetch
        conversionStrategy: Default
        decodingStrategy: None