---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runners-secret-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runners-controller-secret-reader
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: actions-runner-controller-gha-rs-controller
    namespace: actions-runner-controller
roleRef:
  kind: Role
  name: github-runners-secret-reader
  apiGroup: rbac.authorization.k8s.io
