all:
  vars:
    control_plane_endpoint: 192.168.0.100
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        # mirkwood
        metal0: {ansible_host: 192.168.0.11, mac: 'bc:24:11:ad:b2:f3', disk: sda, network_interface: ens18}
        # rohan
        metal1: {ansible_host: 192.168.0.12, mac: 'bc:24:11:1f:7d:4c', disk: sda, network_interface: ens18}
        # gondor
        metal2: {ansible_host: 192.168.0.13, mac: 'bc:24:11:fb:35:66', disk: sda, network_interface: ens18}
    workers:
      hosts:
        #metal4: {ansible_host: 192.168.0.11, mac: 'bc:24:11:5a:10:8b', disk: sda, network_interface: ens18}
        #metal5: {ansible_host: 192.168.0.12, mac: 'bc:24:11:ae:97:ed', disk: sda, network_interface: ens18}
        #metal6: {ansible_host: 192.168.0.13, mac: 'BC:24:11:5E:6D:4F', disk: sda, network_interface: ens18}
   