{{- if .Values.infrastructure.ceph.enabled }}
# External Ceph ServiceMonitor for Proxmox Ceph cluster
# Requires: ceph mgr module enable prometheus (run on any Proxmox node)
#
# NOTE: ArgoCD excludes Endpoints and EndpointSlice resources globally.
# The Endpoints resource below is rendered but not synced by ArgoCD.
# It must be created manually:
#   kubectl apply -f - <<EOF
#   apiVersion: v1
#   kind: Endpoints
#   metadata:
#     name: ceph-mgr-external
#     namespace: monitoring-system
#   subsets:
#     - addresses:
#         - ip: "192.168.0.2"
#         - ip: "192.168.0.202"
#         - ip: "192.168.0.102"
#       ports:
#         - name: metrics
#           port: 9283
#   EOF
---
# Using EndpointSlice instead of Endpoints (Endpoints are excluded by ArgoCD)
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ceph-mgr-external
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ceph-mgr-external
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: exporter
    kubernetes.io/service-name: ceph-mgr-external
addressType: IPv4
ports:
  - name: metrics
    port: {{ .Values.infrastructure.ceph.mgrPort | default 9283 }}
    protocol: TCP
endpoints:
  {{- range .Values.infrastructure.ceph.mgrTargets }}
  - addresses:
      - {{ . | quote }}
    conditions:
      ready: true
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mgr-external
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ceph-mgr-external
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.infrastructure.ceph.mgrPort | default 9283 }}
      targetPort: metrics
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceph-mgr-external
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ceph-mgr-external
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: servicemonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ceph-mgr-external
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 15s
      path: /metrics
      honorLabels: true
{{- end }}
