{{- if .Values.infrastructure.proxmox.enabled }}
---
# Proxmox API Token authentication (recommended over password)
# Vaultwarden item: monitoring-proxmox
# Required custom fields: user, token_name, token_value, verify_ssl
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-exporter-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: proxmox-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields
  target:
    name: proxmox-exporter-secret
    creationPolicy: Owner
  data:
    # User in format: user@realm (e.g., prometheus@pve)
    - secretKey: PVE_USER
      remoteRef:
        key: monitoring-proxmox
        property: user
    # Token name only (e.g., monitoring)
    - secretKey: PVE_TOKEN_NAME
      remoteRef:
        key: monitoring-proxmox
        property: token_name
    # The secret token value from Proxmox (shown only once when created)
    - secretKey: PVE_TOKEN_VALUE
      remoteRef:
        key: monitoring-proxmox
        property: token_value
    - secretKey: PVE_VERIFY_SSL
      remoteRef:
        key: monitoring-proxmox
        property: verify_ssl
{{- end }}

{{- if .Values.infrastructure.opnsense.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-exporter-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opnsense-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-fields
  target:
    name: opnsense-exporter-secret
    creationPolicy: Owner
  data:
    - secretKey: OPNSENSE_API_KEY
      remoteRef:
        key: monitoring-opnsense
        property: api_key
    - secretKey: OPNSENSE_API_SECRET
      remoteRef:
        key: monitoring-opnsense
        property: api_secret
{{- end }}

{{- if .Values.infrastructure.adguard.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-exporter-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: adguard-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden-login
  target:
    name: adguard-exporter-secret
    creationPolicy: Owner
  data:
    - secretKey: ADGUARD_USERNAME
      remoteRef:
        key: monitoring-adguard
        property: username
    - secretKey: ADGUARD_PASSWORD
      remoteRef:
        key: monitoring-adguard
        property: password
{{- end }}
