{{- if .Values.infrastructure.snmp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  snmp.yml: |
    auths:
      public_v2:
        community: public
        security_level: noAuthNoPriv
        auth_protocol: MD5
        priv_protocol: DES
        version: 2
    modules:
      # Standard IF-MIB for interface statistics
      if_mib:
        walk:
          - 1.3.6.1.2.1.1        # system
          - 1.3.6.1.2.1.2        # interfaces
          - 1.3.6.1.2.1.31.1.1   # ifXTable
        metrics:
          - name: sysUpTime
            oid: 1.3.6.1.2.1.1.3
            type: gauge
            help: The time since the network management portion of the system was last re-initialized.
          - name: sysName
            oid: 1.3.6.1.2.1.1.5
            type: DisplayString
            help: An administratively-assigned name for this managed node.
          - name: ifNumber
            oid: 1.3.6.1.2.1.2.1
            type: gauge
            help: The number of network interfaces present on this system.
          - name: ifDescr
            oid: 1.3.6.1.2.1.2.2.1.2
            type: DisplayString
            help: A textual string containing information about the interface.
            indexes:
              - labelname: ifIndex
                type: gauge
          - name: ifOperStatus
            oid: 1.3.6.1.2.1.2.2.1.8
            type: gauge
            help: The current operational state of the interface.
            indexes:
              - labelname: ifIndex
                type: gauge
          - name: ifInOctets
            oid: 1.3.6.1.2.1.2.2.1.10
            type: counter
            help: The total number of octets received on the interface.
            indexes:
              - labelname: ifIndex
                type: gauge
          - name: ifOutOctets
            oid: 1.3.6.1.2.1.2.2.1.16
            type: counter
            help: The total number of octets transmitted out of the interface.
            indexes:
              - labelname: ifIndex
                type: gauge
          - name: ifHCInOctets
            oid: 1.3.6.1.2.1.31.1.1.1.6
            type: counter
            help: The total number of octets received on the interface (64-bit).
            indexes:
              - labelname: ifIndex
                type: gauge
          - name: ifHCOutOctets
            oid: 1.3.6.1.2.1.31.1.1.1.10
            type: counter
            help: The total number of octets transmitted out of the interface (64-bit).
            indexes:
              - labelname: ifIndex
                type: gauge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snmp-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snmp-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: exporter
    spec:
      containers:
        - name: snmp-exporter
          image: prom/snmp-exporter:{{ .Values.infrastructure.snmp.imageTag }}
          args:
            - --config.file=/etc/snmp_exporter/snmp.yml
          ports:
            - name: metrics
              containerPort: 9116
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /etc/snmp_exporter
      volumes:
        - name: config
          configMap:
            name: snmp-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: metrics
      port: 9116
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: snmp-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  endpoints:
    {{- range .Values.infrastructure.snmp.targets }}
    - port: metrics
      interval: 60s
      scrapeTimeout: 30s
      params:
        module:
          - {{ .module }}
        target:
          - {{ .address }}
        auth:
          - public_v2
      path: /snmp
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
        - sourceLabels: [__param_target]
          targetLabel: target
        - targetLabel: device
          replacement: {{ .name }}
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "^snmp_(.*)$"
          targetLabel: __name__
          replacement: "snmp_${1}"
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: snmp-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
