rook-ceph-cluster:
  cephClusterSpec:
    external:
      enable: true
    crashCollector:
      disable: true
    healthCheck:
      daemonHealth:
        mon:
          disabled: false
          interval: 45s
  # -- A list of CephBlockPool configurations to deploy
  # @default -- See [below](#ceph-block-pools)
  cephBlockPools: {}

  # -- A list of CephFileSystem configurations to deploy
  # @default -- See [below](#ceph-file-systems)
  cephFileSystems: {}

  # -- A list of CephObjectStore configurations to deploy
  # @default -- See [below](#ceph-object-stores)
  cephObjectStores: {}