nextcloud:
  nextcloud:
    host: nextcloud.themainfreak.com
    datadir: /var/www/data
    extraVolumes:
    - name: nfs-data
      nfs:
        server: 192.168.0.41
        path: /nfs/nextcloud
    extraVolumeMounts:
    - name: nfs-data
      mountPath: "/var/www/data"
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      # Disabled because of the error " denied the request: nginx.ingress.kubernetes.io/server-snippet annotation cannot be used. Snippet directives are disabled by the Ingress administrator
      # nginx.ingress.kubernetes.io/server-snippet: |-
      #   server_tokens off;
      #   proxy_hide_header X-Powered-By;
      #   rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      #   rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      #   rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      #   rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      #   location = /.well-known/carddav {
      #     return 301 $scheme://$host/remote.php/dav;
      #   }
      #   location = /.well-known/caldav {
      #     return 301 $scheme://$host/remote.php/dav;
      #   }
      #   location = /robots.txt {
      #     allow all;
      #     log_not_found off;
      #     access_log off;
      #   }
      #   location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
      #     deny all;
      #   }
      #   location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
      #     deny all;
      #   }
    hosts:
      - host: &host nextcloud.themainfreak.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - nextcloud.themainfreak.com
        secretName: "nextcloud-tls-certificate"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
      