app-template:
  controllers:
    navidrome:
      securityContext:
        runAsUser: ${APP_UID}
        runAsGroup: ${APP_GID}
        fsGroup: ${APP_GID}
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 65539

    containers:
      app:
        image:
          repository: ghcr.io/navidrome/navidrome
          tag: 0.53.3

        env:
          ND_DATAFOLDER: /data
          ND_ENABLEDOWNLOADS: "true"
          ND_ENABLEEXTERNALSERVICES: "false"
          ND_ENABLESHARING: "false"
          ND_ENABLESTARRATING: "false"
          ND_LOGLEVEL: info
          ND_MUSICFOLDER: /music/
          ND_PORT: &port 4533
          ND_SCANSCHEDULE: 30m

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

        resources:
          requests:
            cpu: 5m
            memory: 799M
          limits:
            memory: 799M

    service:
      app:
        controller: navidrome
        ports:
          http:
            port: *port

    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: &host navidrome.themainfreak.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: navidrome-tls-certificate

    persistence:
      data:
        accessMode: ReadWriteOnce
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi

      media:
        type: nfs
        server: 192.168.0.41
        path: /nfs/plex
        globalMounts:
          - path: /music


