renovate:
  cronjob:
    schedule: '0 9 * * *'  # Everyday at 09:00
  renovate:
    config: |
      {
        "platform": "github",
        "endpoint": "https://github.com/api/v3",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true,
        "autodiscoverFilter": "/fahdr/*"
      }
  # Using github full token. Change to fine grain token
  existingSecret: renovate-secret
