---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vaultwarden-login
spec:
  provider:
    webhook:
      url: "http://vaultwarden-cli.{{ .Release.Namespace }}:8087/object/item/{{`{{ .remoteRef.key }}`}}"
      headers:
        Content-Type: application/json
      result:
        jsonPath: "$.data.login.{{`{{ .remoteRef.property }}`}}"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vaultwarden-fields
spec:
  provider:
    webhook:
      url: "http://vaultwarden-cli.{{ .Release.Namespace }}:8087/object/item/{{`{{ .remoteRef.key }}`}}"
      result:
        jsonPath: "$.data.fields[?@.name==\"{{`{{ .remoteRef.property }}`}}\"].value"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vaultwarden-notes
spec:
  provider:
    webhook:
      url: "http://vaultwarden-cli.{{ .Release.Namespace }}:8087/object/item/{{`{{ .remoteRef.key }}`}}"
      result:
        jsonPath: "$.data.notes"
