---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-cli-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: global-secrets
    kind: ClusterSecretStore
  target:
    name: vaultwarden-cli
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: vaultwarden-cli
      type: Opaque
      data:
        BW_HOST: {{ "https://vaultwarden.themainfreak.com" | b64enc | quote }}
        BW_CLIENTID: {{ "{{ .vaultwarden_client_id }}" | quote }}
        BW_CLIENTSECRET: {{ "{{ .vaultwarden_client_secret }}" | quote }}
  data:
    - secretKey: vaultwarden_client_id
      remoteRef:
        key: external
        property: vaultwarden-client-id
    - secretKey: vaultwarden_client_secret
      remoteRef:
        key: external
        property: vaultwarden-client-secret
