apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-cli
  namespace: global-secrets
type: Opaque
data:
  # Base64 encoded Vaultwarden connection details
  # These will be populated by the extra-secrets module during Terraform deployment
  BW_HOST: {{ "https://vaultwarden.themainfreak.com" | b64enc | quote }}
  BW_CLIENTID: {{ index .Values.secrets "vaultwarden-client-id" | b64enc | quote }}
  BW_CLIENTSECRET: {{ index .Values.secrets "vaultwarden-client-secret" | b64enc | quote }}
