apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-cli
  namespace: global-secrets
type: Opaque
data:
  # Base64 encoded Vaultwarden connection details
  # These are copied from the external secret created by Terraform
  BW_HOST: {{ "https://vaultwarden.themainfreak.com" | b64enc | quote }}
  BW_CLIENTID: ""   # This will be populated by referencing the external secret
  BW_CLIENTSECRET: ""   # This will be populated by referencing the external secret
---
# Job to copy credentials from external secret to vaultwarden-cli secret
apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden-secret-setup
  namespace: global-secrets
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: secret-copier
      containers:
      - name: secret-copier
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Copy client credentials from external secret to vaultwarden-cli secret
          CLIENT_ID=$(kubectl get secret external -n global-secrets -o jsonpath='{.data.vaultwarden-client-id}')
          CLIENT_SECRET=$(kubectl get secret external -n global-secrets -o jsonpath='{.data.vaultwarden-client-secret}')
          
          kubectl patch secret vaultwarden-cli -n global-secrets --type='merge' -p="{\"data\":{\"BW_CLIENTID\":\"$CLIENT_ID\",\"BW_CLIENTSECRET\":\"$CLIENT_SECRET\"}}"
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-copier
  namespace: global-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-copier
  namespace: global-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-copier
  namespace: global-secrets
subjects:
- kind: ServiceAccount
  name: secret-copier
  namespace: global-secrets
roleRef:
  kind: Role
  name: secret-copier
  apiGroup: rbac.authorization.k8s.io
