---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-cli-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: global-secrets
    kind: ClusterSecretStore
  target:
    name: vaultwarden-cli
    creationPolicy: Owner
  data:
    - secretKey: BW_CLIENTID
      remoteRef:
        key: external
        property: vaultwarden-client-id
    - secretKey: BW_CLIENTSECRET
      remoteRef:
        key: external
        property: vaultwarden-client-secret
---
# Simple secret for BW_HOST since it's just a static value
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-cli-host
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  BW_HOST: "https://vaultwarden.themainfreak.com"
