{{- $resticSecret := (default dict .Values.resticSecret) }}
{{- if or (not (hasKey .Values "resticSecret")) (default true $resticSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ get $resticSecret "name" | default (printf "%s-volsync-secret" .Release.Name) | quote }}
#  namespace: {{ get $resticSecret "namespace" | default .Release.Namespace | quote }}
type: Opaque
stringData:
  RESTIC_REPOSITORY: {{ get $resticSecret "repository" | default (printf "/repository/%s" .Release.Name) | quote }}
  RESTIC_PASSWORD: {{ get $resticSecret "password" | default "1234" | quote }}
{{- end }}

