apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-wp
spec:
  minReplicas: 1
  maxReplicas: {{ .Values.wordpress.hpa.maxReplicas | default 10 }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.wordpress.hpa.cpuUtilization | default 80 }}
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-wp