apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-kubernetes-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: true
    traefik: false
