apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inteldeviceplugins-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: webhook-server-cert
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - {{ .Release.Namespace }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - inteldeviceplugins-webhook-service.{{ .Release.Namespace }}.svc
    - inteldeviceplugins-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
