wordpress-site:
  # --- MariaDB dependency options ---
  mariadb:
    replicas: 3
    #user: ""  # If empty, defaults to "<release-name>-user"
    storage:
      size: 1Gi
      #storageClassName: ""  # Optional, set to override default storage class
    replication:
      enabled: true
    primaryService:
      type: ClusterIP
    secondaryService:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  wordpress:
    wordpress:

      db:
        secretKeyRefName: case10-mariadb-secrets
        secretKeyRefKey: "MARIADB_PASSWORD"
      ingress:
        host: case10.themainfreak.com
