{{- $volsyncPVC := (default dict .Values.volsyncPVC) }}
{{- $pvcName := (get $volsyncPVC "name" | default .Release.Name) }}
{{- $replicationDestination := (default dict .Values.replicationDestination) }}
{{- $dataSourceRefName := (get $replicationDestination "name" | default (printf "%s-dst" $pvcName)) }}

{{- if and (or (not (hasKey .Values "volsyncPVC")) (default true $volsyncPVC.enabled)) (not (default false $volsyncPVC.existingClaim)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName | quote }}
#  namespace: {{ get $volsyncPVC "namespace" | default .Release.Namespace | quote }}
spec:
  accessModes: {{ get $volsyncPVC "accessModes" | default (list "ReadWriteOnce") | toJson }}
  dataSourceRef:
    kind: "ReplicationDestination"
    apiGroup: "volsync.backube"
    name: {{ $dataSourceRefName | quote }}
  resources:
    requests:
      storage: {{ get $volsyncPVC "storage" | default "1Gi" | quote }}
  storageClassName: {{ get $volsyncPVC "storageClassName" | default "ceph-block" }}
{{- end }}