{{- $resticSecret := (default dict .Values.resticSecret) }}
{{- $volsyncPVC := (default dict .Values.volsyncPVC) }}
{{- $pvcName := (get $volsyncPVC "name" | default .Release.Name) }}
{{- $resticSecretName := (get $resticSecret "name" | default (printf "%s-volsync-secret" $pvcName)) }}
{{- if or (not (hasKey .Values "resticSecret")) (default true $resticSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $resticSecretName | quote }}
#  namespace: {{ get $resticSecret "namespace" | default .Release.Namespace | quote }}
type: Opaque
stringData:
  RESTIC_REPOSITORY: {{ get $resticSecret "repository" | default (printf "/repository/%s" $pvcName) | quote }}
  RESTIC_PASSWORD: {{ get $resticSecret "password" | default "1234" | quote }}
{{- end }}

