apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secrets
  labels:
    k8s.mariadb.com/watch:
stringData:
  MARIADB_PASSWORD: {{ randAlphaNum 16 | quote }}
  MARIADB_ROOT_PASSWORD: {{ randAlphaNum 16 | quote }}
  MARIADB_REPL_PASSWORD: {{ randAlphaNum 16 | quote }}
  MINIO_ACCESS_KEY: {{ randAlphaNum 16 | quote }}
  MINIO_SECRET_KEY: {{ randAlphaNum 32 | quote }}