{{- if not .Values.mariadb.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secrets
  labels:
    k8s.mariadb.com/watch:
stringData:
  MARIADB_PASSWORD: {{ .Values.mariadb.passwords.user | default (randAlphaNum 16) | quote }}
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.passwords.root | default "abcd1234" | quote }}
  MARIADB_REPL_PASSWORD: {{ .Values.mariadb.passwords.replication | default (randAlphaNum 16) | quote }}
  MINIO_ACCESS_KEY: {{ .Values.mariadb.passwords.minioAccessKey | default (randAlphaNum 16) | quote }}
  MINIO_SECRET_KEY: {{ .Values.mariadb.passwords.minioSecretKey | default (randAlphaNum 32) | quote }}
{{- end }}