{{- if not .Values.mariadb.externalSecret.enabled }}
{{- $secretName := printf "%s-mariadb-secrets" .Release.Name }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    k8s.mariadb.com/watch: ""
  annotations:
    helm.sh/resource-policy: keep
stringData:
{{- if $existingSecret }}
  MARIADB_PASSWORD: {{ index $existingSecret.data "MARIADB_PASSWORD" | b64dec | quote }}
  MARIADB_ROOT_PASSWORD: {{ index $existingSecret.data "MARIADB_ROOT_PASSWORD" | b64dec | quote }}
  MARIADB_REPL_PASSWORD: {{ index $existingSecret.data "MARIADB_REPL_PASSWORD" | b64dec | quote }}
  MINIO_ACCESS_KEY: {{ index $existingSecret.data "MINIO_ACCESS_KEY" | b64dec | quote }}
  MINIO_SECRET_KEY: {{ index $existingSecret.data "MINIO_SECRET_KEY" | b64dec | quote }}
{{- else }}
  MARIADB_PASSWORD: {{ .Values.mariadb.passwords.user | default (randAlphaNum 16) | quote }}
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.passwords.root | default (randAlphaNum 24) | quote }}
  MARIADB_REPL_PASSWORD: {{ .Values.mariadb.passwords.replication | default (randAlphaNum 16) | quote }}
  MINIO_ACCESS_KEY: {{ .Values.mariadb.passwords.minioAccessKey | default (randAlphaNum 16) | quote }}
  MINIO_SECRET_KEY: {{ .Values.mariadb.passwords.minioSecretKey | default (randAlphaNum 32) | quote }}
{{- end }}
{{- end }}
