---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Immich
        JWT_SECRET: "{{ .immich_jwt_secret }}"
        TYPESENSE_API_KEY: "{{ .immich_typesense_api_key }}"
  dataFrom:
    - extract:
        key: immich
      rewrite:
        - regexp:
            source: "(.*)"
            target: "immich_$1"