# ApplicationSet for automatic deployment of feature branches
# Only deploys apps that have a .deploy-to-dev marker file
argocd-apps:
  applicationsets:
    dev:
      namespace: argocd
      generators:
        - git:
            repoURL: &repoURL https://github.com/fahdr/portkey
            revision: &revision feature/*  # This will track all feature branches
            files:
              - path: "apps/*/.deploy-to-dev"  # Only deploy if this marker file exists
      template:
        metadata:
          name: 'dev-{{path[1]}}-{{branch}}'  # path[1] gives us the app name
          annotations:
            argocd.argoproj.io/compare-options: IgnoreExtraneous
            argocd.argoproj.io/sync-options: Delete=false  # Don't auto-delete when testing
            testing.portkey.io/created-by: applicationset
            testing.portkey.io/source-branch: '{{branch}}'
        spec:
          destination:
            name: in-cluster
            namespace: 'dev-{{path[1]}}'  # Use dev- prefix for namespaces
          project: default
          source:
            repoURL: *repoURL
            path: 'apps/{{path[1]}}'  # Deploy the specific app
            targetRevision: '{{branch}}'  # Deploy from the feature branch
          syncPolicy:
            automated:
              prune: false  # Don't auto-prune during testing
              selfHeal: false  # Don't auto-heal during testing
            retry:
              limit: 5
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 8m
            syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true
