apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-bluetooth
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true # Recommended unless using very exact udev rules
      udevRules:
      - ATTRS{idVendor}=="8087", ATTRS{idProduct}=="07dc"
    name: udev