name: Deploy Helm Charts to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'charts-common/**'
      - '.github/workflows/deploy-charts.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
      contents: read
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      # Steps for common-charts/common
      - name: Package Helm charts (common)
        run: |
          mkdir -p packaged
          helm package --dependency-update charts-common/common/* --destination packaged/

      - name: Create Helm repo index (common)
        run: |
          helm repo index packaged --url https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}/

      - name: Upload static files as artifact (common)
        id: deployment_common
        uses: actions/upload-pages-artifact@v3
        with:
          path: packaged/

      - name: Deploy to GitHub Pages (common)
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ steps.deployment_common.outputs.artifact_name }}

      # Steps for common-charts/bootstrap
      - name: Package Helm charts (bootstrap)
        run: |
          mkdir -p packaged
          helm package --dependency-update charts-common/bootstrap/* --destination packaged/
      
      - name: Create Helm repo index (bootstrap)
        run: |
          helm repo index packaged --url https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}
          ls packaged
          cat packaged/index.yaml
      - name: Upload static files as artifact (bootstrap)
        id: deployment_bootstrap
        uses: actions/upload-pages-artifact@v3
        with:
          path: packaged
          name: bootstrap

      - name: Deploy to GitHub Pages (bootstrap)
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ steps.deployment_bootstrap.outputs.artifact_name }}

