name: Deploy Helm Charts to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'charts-common/**'
      - '.github/workflows/deploy-charts.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Package Helm charts
        run: |
          mkdir -p packaged
          rm -rf charts-common/wordpress-site
          helm package charts-common/* --destination packaged

      - name: Create Helm repo index
        run: |
          helm repo index packaged --url https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}

      - name: Upload Helm charts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: packaged
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

